project 'CryptoEye.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CryptoEye' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
pod 'lottie-ios'
pod 'Firebase/Core'
pod 'ios-linechart', '~> 1.3'
pod 'drCharts', :git => 'https://github.com/Zomato/DR-charts.git'
pod 'MaterialComponents'
pod 'Firebase/Messaging'
pod 'SCLAlertView-Objective-C', '~> 1.1'
pod 'Firebase/AdMob'
end
